services:
  pasarguard:
    build:
      context: /opt/pasarguard/panel
      dockerfile: Dockerfile
    restart: always
    env_file: /opt/pasarguard/.env
    network_mode: host
    volumes:
      - /var/lib/pasarguard:/var/lib/pasarguard
